### ISSUE TITLE
PNG images lose transparency

### ISSUE THREAD

**Issue by eyuelad** [benwinding/quill-image-compress#16]

**Comment by benwinding** [comment]
This is due to how the image is compressed. It's compressed by loading the image onto a canvas, then shrinking the canvas and getting a screenshot of the canvas. This is the function below:

https://github.com/benwinding/quill-image-compress/blob/30e686abbd683fd00523338fafaf633ab3cedfb7/src/quill.imageCompressor.js#L159-L208

Not sure how we can retain transparency from that, any ideas?

**Comment by benwinding** [comment]
Hi @eyuelad,
This is fixed by simply setting the `imageType` field to `image/png` in the plugin settings.
``` js
var quill = new Quill("#editor", {
  theme: "snow",
  modules: {
    toolbar: {
      container: fullToolbarOptions
    },
    imageCompressor: {
      quality: 0.9,
      maxWidth: 200,
      maxHeight: 200,
      imageType: 'image/png',
      debug: true
    },
  }
});
```
![image](https://user-images.githubusercontent.com/11782590/113293209-03255b00-933d-11eb-9bd1-7348510ac9c9.png)
